### ISSUE TITLE
Calling rake db:seed_fu invokes factory_girl initialization

### ISSUE THREAD

**Issue by nagyt234** [thoughtbot/factory_girl_rails#168]
I don't understand why `rake db:seed_fu` invokes factory_girl initialization, causing exception in my system (the short trace):
```
/var/www/html/dev/rails/v2p0(1054)>rake db:seed_fu RAILS_ENV=test
rake aborted!
NoMethodError: undefined method `id' for nil:NilClass
/var/www/html/dev/rails/v2p0/spec/factories.rb:7:in `block (2 levels) in <top (required)>'
/var/www/html/dev/rails/v2p0/spec/factories.rb:4:in `block in <top (required)>'
/var/www/html/dev/rails/v2p0/spec/factories.rb:3:in `<top (required)>'
/var/www/html/dev/rails/v2p0/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:seed_fu => environment
(See full trace by running task with --trace)
```
I have a fragment in spec/factories.rb which needs some records already loaded into the  database. They should be loaded with `rake db:seed_fu`:
```
  factory :document do
    sequence(:code)  { |n| "DOC-#{(n.to_s.rjust(Settings.SXS.Application.Documents.CodeNumLength,'0'))}" }
    folder nil
    resource_sub_type_id ResourceSubType.get_default_by_resource(Document).id
  end
```
This worked in rails 3.2.21, but the error cames up as I upgraded to rails 4.1.9. I have the following code in `config/application.rb`
```
    # Use RSpec as test framework
    config.generators do |g|
      g.test_framework :rspec,
        :fixtures => true,
        :view_specs => false,
        :helper_specs => false,
        :routing_specs => true,
        :controller_specs => true,
        :request_specs => true
      g.stylesheets false
      g.factory_girl false
    end
```
The full error trace if it helps:
```
/var/www/html/dev/rails/v2p0(1055)>rake db:seed_fu RAILS_ENV=test --trace
** Invoke db:seed_fu (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `id' for nil:NilClass
/var/www/html/dev/rails/v2p0/spec/factories.rb:7:in `block (2 levels) in <top (required)>'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:18:in `instance_eval'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:18:in `factory'
/var/www/html/dev/rails/v2p0/spec/factories.rb:4:in `block in <top (required)>'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:49:in `run'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/syntax/default.rb:7:in `define'
/var/www/html/dev/rails/v2p0/spec/factories.rb:3:in `<top (required)>'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `block in load'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:241:in `load'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:16:in `block in find_definitions'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:15:in `each'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/factory_girl-4.5.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/factory_girl_rails-4.5.0/lib/factory_girl_rails/railtie.rb:21:in `block in <class:Railtie>'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:36:in `call'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:44:in `each'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/railties-4.1.9/lib/rails/application/finisher.rb:64:in `block in <module:Finisher>'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `instance_exec'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/railties-4.1.9/lib/rails/initializable.rb:30:in `run'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/railties-4.1.9/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/tsort.rb:345:in `each'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/tsort.rb:345:in `call'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/tsort.rb:224:in `tsort_each'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/tsort.rb:203:in `tsort_each'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/railties-4.1.9/lib/rails/initializable.rb:54:in `run_initializers'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/railties-4.1.9/lib/rails/application.rb:300:in `initialize!'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `public_send'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/railties-4.1.9/lib/rails/railtie.rb:194:in `method_missing'
/var/www/html/dev/rails/v2p0/config/environment.rb:5:in `<top (required)>'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `block in require'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:232:in `load_dependency'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/activesupport-4.1.9/lib/active_support/dependencies.rb:247:in `require'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/railties-4.1.9/lib/rails/application.rb:276:in `require_environment!'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/railties-4.1.9/lib/rails/application.rb:405:in `block in run_tasks_blocks'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/task.rb:240:in `call'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/task.rb:235:in `each'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/task.rb:235:in `execute'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/task.rb:199:in `each'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/task.rb:165:in `invoke'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/application.rb:106:in `each'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/application.rb:100:in `top_level'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/application.rb:78:in `block in run'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/2.2.0/rake/application.rb:75:in `run'
/home/ntibor/.rbenv/versions/2.2.2/lib64/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/ntibor/.rbenv/versions/2.2.2/bin/rake:23:in `load'
/home/ntibor/.rbenv/versions/2.2.2/bin/rake:23:in `<main>'
Tasks: TOP => db:seed_fu => environment
```

**Comment by joshuaclayton** [comment]
@nagyt234 I'd make the following update:

```ruby
# old
resource_sub_type_id ResourceSubType.get_default_by_resource(Document).id
#new
resource_sub_type_id { ResourceSubType.get_default_by_resource(Document).id }
```

This ensures the calculation of resource sub type is calculated when that method is invoked instead of when the file is loaded.

To answer your other question, FG is loaded by default when you're running in a test environment (you'd mentioned running `rake db:seed_fu RAILS_ENV=test`).

Hope this helps!
